FROM phusion/baseimage:0.9.18

MAINTAINER Paixon GmbH
MAINTAINER jaycyb <dev.cyborg@gmail.com>

ADD runagent.sh /home/teamcity/runagent.sh

RUN echo "oracle-java7-installer  shared/accepted-oracle-license-v1-1 boolean true" | /usr/bin/debconf-set-selections \
 && add-apt-repository ppa:webupd8team/java \
 && apt-get update \
 && DEBIAN_FRONTEND="noninteractive" apt-get install -q -y oracle-java8-installer oracle-java8-set-default unzip wget \
 && apt-get remove openjdk-7-jre \
 && apt-get update \
 && chmod +x /home/teamcity/runagent.sh \
 && adduser teamcity

CMD ["/home/teamcity/runagent.sh"]
